### ISSUE TITLE
libnpmconfig deprecation warning

### ISSUE THREAD

**Issue by ralphtheninja** [vweevers/hallmark#101]
I get a deprecation warning for `libnpmconfig`:

`npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config`

```
$ npm ls libnpmconfig
└─┬ hallmark@4.1.0
  └─┬ unified-engine@9.1.1
    └─┬ load-plugin@4.0.1
      └── libnpmconfig@1.2.1
```

Not sure what the best way would be to get rid of it. Upgrade to `@npmcli/config`?

**Comment by vweevers** [comment]
We should get `@npmcli/config` if we upgrade `unified-engine`.

**Comment by ralphtheninja** [comment]
PR welcome?

**Comment by vweevers** [comment]
Ah we already have a PR: https://github.com/vweevers/hallmark/pull/98. Seems like it's good to merge too, I just forgot about it. If you could verify that it includes the npm module, that'd be great. Nice to see you btw!

**Comment by vweevers** [comment]
Maybe we should merge https://github.com/vweevers/hallmark/pull/100 at the same time as it also depends on `unified-engine`.

**Comment by ralphtheninja** [comment]
> Maybe we should merge #100 at the same time as it also depends on `unified-engine`.

Sounds good!

**Comment by vweevers** [comment]
Having merged both PRs:

```
$ npm ls libnpmconfig
hallmark@4.1.0
└── (empty)
```

I'm making a few unrelated fixes to `remark-common-changelog`, will release afterwards.

**Comment by vweevers** [comment]
[4.2.0](https://github.com/vweevers/hallmark/releases/tag/v4.2.0)
