### ISSUE TITLE
Support [Unreleased] "Release version must be semver-valid"

### ISSUE THREAD

**Issue by koppor** [vweevers/hallmark#103]
On https://github.com/JabRef/jabref/blob/29f5cae6bc26b6622a9306ac908bd7157a53c3dd/CHANGELOG.md?plain=1#L10, I get

```
  ‼      10:1-10:16  Release version must be semver-valid                       remark-common-changelog:release-version
```

I am fully aware that `Unreleased` is not SemVer. However, this is a perfectly valid entry in CHANGELOG.

Context: I would like to use this tool in a GitHub action checking updates of CHANGELOG entries.

**Comment by vweevers** [comment]
Hallmark follows [Common Changelog](https://common-changelog.org/) rather than Keep a Changelog.

> Common Changelog does not have an `Unreleased` section at the top of the changelog, which Keep a Changelog recommends for listing unreleased changes as they land in the main branch of the project. In practice \[..\] this is an unproductive workflow.
> — https://common-changelog.org/#62-how-is-this-different-from-keep-a-changelog

**Comment by koppor** [comment]
> Hallmark follows [Common Changelog](https://common-changelog.org/) rather than Keep a Changelog.

Thank you for letting me know - and the reference for the reasoning.

In our project, it is completely differently. Two maintainers review PRs from a global perspective. They fix the CHANGELOG entry in the PR, because they a) have the local context of the PR and b) have the global context (because they are maintainers). Since we release each 6 months (and, due to reasons, we are usually not faster), we cannot create a CHANGELOG on the release date. This is too much effort for us. Especially, because we don't have the context of the hundreds of PRs from different contributors in mind.
