### ISSUE TITLE
Hallmark with filesystem based remotes ?

### ISSUE THREAD

**Issue by gl-yziquel** [vweevers/hallmark#126]
Hi.

I experienced the following error with a homebuilt hallmark. From source.

I get the following error:

 Unable to parse git host URL "/storage/git/my-repo.git/".

I tend to store my git repositories in a storage space, to buffer my interactions with the remotes through that repository. And then, I clone that filesystem based repository to work on it locally.

When running `hallmark` on that repository, it seems to have a problem with filesystem based, local, git remotes.

Is this considered a problem for `hallmark` ? Or not ?

**Comment by vweevers** [comment]
It tries to guess the URL of your GitHub (or similar) repository based on the git remote. When that's not possible, like in your case, you can create a [`.hallmarkrc`](https://github.com/vweevers/hallmark?tab=readme-ov-file#package-options) file containing:

```
{
  "repository": "owner/repo"
}
```

**Comment by gl-yziquel** [comment]
Thank you.

A cli option to perform only markdown formatting and ignore the remotes would suit my workflow better. But, OK.

**Comment by vweevers** [comment]
It is used for formatting in the [`remark-github`](https://github.com/remarkjs/remark-github) plugin and others. If you want less, you might prefer [`remark-cli`](https://www.npmjs.com/package/remark-cli).

**Comment by gl-yziquel** [comment]
Thank you !
