### ISSUE TITLE
Link changelog headers to GitHub release instead of diff URL

### ISSUE THREAD

**Issue by vweevers** [vweevers/hallmark#82]
The diff URL - for example [6.0.0](https://github.com/Level/leveldown/compare/v5.6.0...v6.0.0) - is something we adapted from Keep A Changelog but I now prefer linking to the GitHub release - for example [6.0.0](https://github.com/Level/leveldown/releases/tag/v6.0.0) - because it's richer. It has assets, the compare button which does the same as our diff URL, etc. Plus it works on the first release too.

**Comment by ralphtheninja** [comment]
We could have a diff link as well?

**Comment by ralphtheninja** [comment]
> the compare button which does the same as our diff URL

Ah nvm.
